# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "projethx-tg-state"
    dynamodb_table = "projethx-tg-lock"
    encrypt        = true
    key            = "./terraform.tfstate"
    profile        = "projethx-main"
    region         = "eu-central-1"
  }
}
