# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  profile = "projethx-main"
  region  = "eu-central-1"
}

provider "aws" {
  alias   = "eu-central-1"
  profile = "projethx-main"
  region  = "eu-central-1"
}
